branch-defaults:
  default:
    environment: groupby-v4
    group_suffix: null
environment-defaults:
  groupby-1:
    branch: null
    repository: null
global:
  application_name: GroupByDemo
  branch: null
  default_ec2_keyname: groupby
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
